---
- hosts: all

  vars_files:
    - default.yml

  tasks:
  - name: stat host vars file
    stat:
      path: "{{ host_vars_file_path }}"
    register: stat_host_vars_file

  - name: Include host vars
    include_vars:
      file: "{{ playbook_dir }}/vars/host.yml"
    when: stat_host_vars_file.stat is defined and stat_host_vars_file.stat.exists

  - import_tasks: tasks/user_inputs.yml
    tags: ['user_inputs']

  - import_tasks: tasks/prepare.yml
    tags: ['prepare']

  - import_tasks: tasks/basic-distribution-preparation.yml
    tags: ['basic-distribution-preparation']

  - import_tasks: tasks/basic-linux-tools.yml
    tags: ['basic-linux-tools']

  - import_tasks: tasks/basic-consumer-tools.yml
    tags: ['basic-consumer-tools']

  - import_tasks: tasks/developer-tools.yml
    tags: ['developer-tools']

  - import_tasks: tasks/personal-tools.yml
    tags: ['personal-tools']

  - import_tasks: tasks/configuration.yml
    tags: ['configuration']

  - import_tasks: tasks/manual-actions.yml
    tags: ['manual-actions']
    when: prompt_for_manual_actions

  - import_tasks: tasks/teardown.yml
    tags: ['teardown']
