---
- hosts: all

  tasks:
  - import_tasks: tasks/timely-apt-update.yml
    tags: ['timely-apt-update']

  - import_tasks: tasks/basic-linux-tools.yml
    tags: ['basic-linux-tools']

#  - apt:
#      name:
#      - meld
#      - jq
#      - tmux
#      - htop
#    become: yes


  - snap:
      name:
      - telegram-desktop
#      - glances
      - vlc
    become: yes
