---
- hosts: all

  vars_files:
    - vars.yml

  tasks:
  - name: Check architecture of packages
    shell: dpkg --print-architecture
    register: dpkg_print_architecture

  - set_fact:
      packages_architecture: "{{dpkg_print_architecture.stdout}}"

  - import_tasks: tasks/timely-apt-update.yml
    tags: ['timely-apt-update']

  - import_tasks: tasks/basic-linux-tools.yml
    tags: ['basic-linux-tools']

  - import_tasks: tasks/basic-consumer-tools.yml
    tags: ['basic-consumer-tools']

  - import_tasks: tasks/developer-tools.yml
    tags: ['developer-tools']

  - import_tasks: tasks/personal-tools.yml
    tags: ['personal-tools']

# TODO install slack (where does it belong?)
# TODO configure desktop, lockscreen (swaylock? - available via apt) and hotkeys (where does it belong?)

# TODO set up aliases
# TODO set up completion
# TODO set up configuration for git and more
# TODO set up SSH keys