---
- hosts: all

  tasks:
  - import_tasks: tasks/timely-apt-update.yml
    tags: ['timely-apt-update']

  - import_tasks: tasks/basic-linux-tools.yml
    tags: ['basic-linux-tools']

  - import_tasks: tasks/basic-consumer-tools.yml
    tags: ['basic-consumer-tools']

  - import_tasks: tasks/developer-tools.yml
    tags: ['developer-tools']

  - import_tasks: tasks/personal-tools.yml
    tags: ['personal-tools']

