---
- hosts: all

  vars_files:
    - vars.yml

  tasks:
  - import_tasks: tasks/user_inputs.yml
    tags: ['user_inputs']

  - import_tasks: tasks/setup.yml
    tags: ['setup']

  - import_tasks: tasks/basic-linux-tools.yml
    tags: ['basic-linux-tools']

  - import_tasks: tasks/basic-consumer-tools.yml
    tags: ['basic-consumer-tools']

  - import_tasks: tasks/developer-tools.yml
    tags: ['developer-tools']

  - import_tasks: tasks/personal-tools.yml
    tags: ['personal-tools']

  - import_tasks: tasks/configuration.yml
    tags: ['configuration']

  - import_tasks: tasks/manual-actions.yml
    tags: ['manual-actions']
    when: "{{prompt_for_manual_actions}}"

  - import_tasks: tasks/teardown.yml
    tags: ['teardown']


# TODO configure desktop, taskbar, lockscreen and hotkeys (where does it belong?)