---
- hosts: localhost
  connection: local
  tasks:
  - apt:
      name:
      - meld
      - jq
      - tmux
      - htop
      update_cache: yes
    become: yes


  - snap:
      name:
      - telegram-desktop
      - glances
      - vlc
    become: yes
