---
- hosts: localhost
  connection: local
  tasks:

  - import_tasks: tasks/timely-apt-update.yml
    tags: ['timely-apt-update']

  - apt:
      name:
      - meld
      - jq
      - tmux
      - htop
    become: yes


  - snap:
      name:
      - telegram-desktop
      - glances
      - vlc
    become: yes
