---
roles:
  - name: cmprescott.chrome
    version: 0.2.5

  - name: geerlingguy.docker
    version: 6.0.2

  - name: geerlingguy.nodejs
    version: 6.1.0

  - name: geerlingguy.go
    version: 1.1.0

  - name: ahuffman.resolv
    version: 1.3.2

  - name: avanov.pyenv
    version: 1.1.0

  - name: robertdebock.terraform
    version: 4.1.3

collections:
  - name: moreati.jq
    version: 0.2.1
