---
roles:
  - name: cmprescott.chrome
    version: 0.2.4

  - name: geerlingguy.docker
    version: 4.1.1

  - name: geerlingguy.nodejs
    version: 6.0.0

  - name: geerlingguy.go
    version: 1.0.0

  - name: ahuffman.resolv
    version: 1.3.2

  - name: avanov.pyenv
    version: 1.1.0

collections:
  - name: moreati.jq
    version: 0.2.1
