---
roles:
  - name: cmprescott.chrome
    version: 0.2.5

  - name: geerlingguy.docker
    version: 7.1.0

  - name: geerlingguy.nodejs
    version: 6.1.1

  - name: geerlingguy.go
    version: 1.1.0

  - name: staticdev.pyenv
    version: 2.11.0

  - name: robertdebock.terraform
    version: 4.1.7

  - name: don_rumata.ansible_role_install_flatpak
    version: v1.0.0

  - name: petermosmans.customize-gnome
    version: 0.2.12
