---
- name: Configure name servers
  import_role:
    name: ahuffman.resolv
  vars:
    resolv_nameservers:
      - "8.8.8.8"
      - "8.8.4.4"

- name: Install basic linux tools (apt)
  apt:
    name:
    - meld
    - jq
    - tmux
    - htop
    - bat
    - hstr
    - ncdu
    - nano
    - ffmpeg
    - python3-distutils-extra
    - net-tools
    - zip
    - unzip
    - traceroute
    - exa
    - zsh
    - simplescreenrecorder
  become: yes

- name: Check if oh-my-zsh is installed
  shell: zsh -ic '[[ -e $ZSH ]]'
  ignore_errors: yes
  register: omz_check

- name: Install oh-my-zsh
  shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended
  when: omz_check.rc != 0

- name: Generate hstr configuration for zsh
  shell: "zsh {{playbook_dir}}/configuration/generate_hstr_configuration.sh"
  register: hstr_configuration_zsh

- name: Save hstr configuration to fill in zshrc
  set_fact:
    hstr_configuration_for_zshrc: "{{ hstr_configuration_zsh.stdout }}"

- name: Install basic linux tools (snap)
  snap:
    name:
    - glances
    - fx
  become: yes

- name: Install basic linux tools (pip)
  pip:
    name:
    - thefuck
  become: yes

- name: Evaluate alias for thefuck
  # 2022-10-19: The output is equivalent for bash and zsh
  # TODO:  make sure it's running in zsh
  shell: thefuck --alias
  register: thefuck_alias

- name: Save thefuck alias to fill in zshrc
  set_fact:
    thefuck_alias_for_zshrc: |
      {{thefuck_alias.stdout}}
      alias f=fuck

- name: Download prettyping
  get_url:
    url: https://raw.githubusercontent.com/denilsonsa/prettyping/master/prettyping
    dest: /opt/prettyping
    mode: "0755"
  become: yes
  register: download_prettyping

- name: Create a symlink to prettyping
  file:
    src: "{{download_prettyping.dest}}"
    dest: /usr/bin/prettyping
    state: link
  become: yes
