- name: Install basic consumer tools (snap)
  snap:
    name:
    - vlc
  become: yes

- name: Install Google Chrome
  import_role:
    name: cmprescott.chrome
  become: yes

- name: Install Zoom
  apt:
    deb: https://zoom.us/client/latest/zoom_{{download_architecture}}.deb
  become: yes

