---
- name: Install basic linux tools (apt)
  apt:
    name:
    - meld
    - jq
    - tmux
    - htop
    - bat  # TODO alias batcat=bat + completion
    - hstr # TODO hstr --show-configuration >> ~/.bashrc
    - ncdu # TODO alias du=ncdu
    - nano
    - ffmpeg
  become: yes

- name: Install basic linux tools (snap)
  snap:
    name:
    - glances
  become: yes

- name: Install basic linux tools (pip)
  pip:
    name:
    - thefuck # TODO put eval "$(thefuck --alias)" in ~/.bashrc, and alias f=fuck
  become: yes

- name: Download prettyping
  get_url:
    url: https://raw.githubusercontent.com/denilsonsa/prettyping/master/prettyping
    dest: /opt/prettyping # TODO add to path or link to /usr/bin/
    mode: '711'
  become: yes