- name: Install basic consumer tools (apt)
  apt:
    name:
    - xournal
  become: yes

- name: Install basic consumer tools (snap)
  snap:
    name:
    - vlc
  become: yes

- name: Install Google Chrome
  import_role:
    name: cmprescott.chrome
  become: yes

- name: Set Google Chrome as the default browser
  shell: kwriteconfig5 --file kdeglobals --group General --key 'BrowserApplication' google-chrome.desktop

- name: Install Zoom
  apt:
    deb: https://zoom.us/client/latest/zoom_{{packages_architecture}}.deb
  become: yes

- name: Install Slack
  snap:
    name: slack
    classic: yes
  become: yes
  when: install_slack