- name: Install basic consumer tools (apt)
  apt:
    name:
    - xournal
  become: yes

- name: Install basic consumer tools (snap)
  snap:
    name:
    - vlc
  become: yes

- name: Add Google linux signing key (for Chrome)
  apt_key:
    url: https://dl-ssl.google.com/linux/linux_signing_key.pub
  become: yes

- name: Add Google Chrome repo
  apt_repository:
    repo: "deb [arch={{packages_architecture}}] http://dl.google.com/linux/chrome/deb/ stable main"
    filename: /etc/apt/sources.list.d/google-chrome.list
    update_cache: yes
  become: yes

- name: Install Google chrome
  apt:
    name: google-chrome-stable
    state: latest
  become: yes

- name: Set Google Chrome as the default browser
  shell: |
    xdg-settings set default-web-browser google-chrome.desktop
    xdg-mime default google-chrome.desktop x-scheme-handler/http
    xdg-mime default google-chrome.desktop x-scheme-handler/https
  when: configure_gnome

- name: Install Zoom
  community.general.flatpak:
    name:
      - us.zoom.Zoom

- name: Install Slack
  snap:
    name: slack
    classic: yes
  become: yes
  when: computer_type == "work"
