---
- name: Install basic linux tools (apt)
  apt:
    name:
    - meld
    - jq
    - tmux
    - htop
    - bat
    - hstr
    - ncdu
    - nano
    - ffmpeg
  become: yes

- name: Generate configuration for hstr
  shell: hstr --show-configuration
  register: hstr_configuration

- name: Add hstr configuration to bash configuration
  lineinfile:
    path: "{{bash_configuration_file_path}}"
    line: "{{hstr_configuration.stdout}}"

- name: Install basic linux tools (snap)
  snap:
    name:
    - glances
  become: yes

- name: Install basic linux tools (pip)
  pip:
    name:
    - thefuck
  become: yes

- name: Evaluate alias for thefuck
  shell: thefuck --alias
  register: thefuck_alias

- name: Add thefuck alias to bash configuration
  lineinfile:
    path: "{{bash_configuration_file_path}}"
    line: "{{thefuck_alias.stdout}}"

- name: Download prettyping
  get_url:
    url: https://raw.githubusercontent.com/denilsonsa/prettyping/master/prettyping
    dest: /opt/prettyping # TODO add to path or link to /usr/bin/
    mode: '711'
  become: yes

# TODO diff-so-fancy