- name: Update .bashrc # TODO fix
  blockinfile:
    block: "{{ lookup('file', bash_configuration_file_path) }}"
    path: "{{ lookup('file', ansible_user_dir+'/.bashrc') }}"
    backup: yes
    marker: "# {mark} ANSIBLE MANAGED BLOCK {{ item.name }}"
    validate: "source {{ansible_user_dir}}/.bashrc"

