- name: Update .bashrc
  blockinfile:
    block: "{{ lookup('file', bash_configuration_file_path) }}"
    path: "{{ lookup('file', ansible_user_dir+'/.bashrc') }}"
    backup: yes
    marker: "# {mark} ANSIBLE MANAGED BLOCK {{ item.name }}"
    validate: "source {{ansible_user_dir}}/.bashrc"

- name: Configure diff-so-fancy in git config
  git_config:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    scope: global
  loop: "{{ config | dict2items }}"
  vars:
    config:
      core.pager: "diff-so-fancy | less --tabs=4 -RFX"
      interactive.diffFilter: "diff-so-fancy --patch"
      color.ui: "true"
      color.diff-highlight.oldNormal: "red bold"
      color.diff-highlight.oldHighlight: "red bold 52"
      color.diff-highlight.newNormal: "green bold"
      color.diff-highlight.newHighlight: "green bold 22"
      color.diff.meta: "11"
      color.diff.frag: "magenta bold"
      color.diff.func: "146 bold"
      color.diff.commit: "yellow bold"
      color.diff.old: "red bold"
      color.diff.new: "green bold"
      color.diff.whitespace: "red reverse"
