---
- name: Update .bashrc
  blockinfile:
    block: "{{ lookup('file', bash_configuration_file_path) }}"
    path: "{{ansible_user_dir}}/.bashrc"
    backup: yes
    marker: "# {mark} ANSIBLE MANAGED BLOCK"

