# TODO: recent python version/pyenv, golang, NodeJS, setup Python venv

- name: Download GH CLI GPG key public ring
  get_url:
    url: https://cli.github.com/packages/githubcli-archive-keyring.gpg
    dest: /usr/share/keyrings/githubcli-archive-keyring.gpg
    mode: '0644'
  become: yes

- name: Add GH CLI repository into sources list
  ansible.builtin.apt_repository:
    repo: "deb [arch={{packages_architecture}} signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main"
    state: present
    filename: /etc/apt/sources.list.d/github-cli.list
  become: yes

- name: Install basic linux tools (apt)
  apt:
    update_cache: yes  # Required to update GH CLI repo
    name:
    - gh
    - git
    - nmap
    - wireshark
  become: yes

- name: Install Docker
  import_role:
    name: geerlingguy.docker
  vars:
    docker_compose_version: "1.29.2"
    docker_apt_arch: "{{packages_architecture}}"
    docker_users:
      - "{{ansible_user_id}}"  # Self user (the user running this setup)
  become: yes

- name: Install dive
  apt:
    deb: "https://github.com/wagoodman/dive/releases/download/v{{dive_version}}/dive_{{dive_version}}_linux_{{packages_architecture}}.deb"
  become: yes

- name: Install JetBrains IDEs
  snap:
    name:
      - pycharm-professional
      - goland
    classic: yes
  become: yes

- name: Install Postman
  snap:
    name: postman
    channel: "{{postman_snap_channel}}"
  become: yes

- name: Download AWS CLI
  get_url:
    url: "https://awscli.amazonaws.com/awscli-exe-linux-{{ansible_architecture}}.zip"
    dest: "{{temp_dir}}/awscli.zip"
  register: download_awscli

- name: Extract AWS CLI
  unarchive:
    src: "{{download_awscli.dest}}"
    dest: "{{temp_dir}}/awscli"
  register: unarchive_awscli

- name: Install AWS CLI
  shell: "{{unarchive_awscli.dest}}/aws/install"
  become: yes
