# TODO: docker, JetBrains IDE(s), recent python version/pyenv, golang

- name: Install developer tools (snap)
  snap:
    name:
    - gh # TODO install from an official source - https://github.com/cli/cli/blob/trunk/docs/install_linux.md#debian-ubuntu-linux-raspberry-pi-os-apt
  become: yes
