---
- name: Download Homebrew installation script
  get_url:
    url: https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh
    dest: "{{temp_dir}}/install.sh"
    mode: "0644"
  register: download_homebrew_installation_script

- name: Install dependencies
  apt:
    name:
      - build-essential
      - procps
      - curl
      - file
      - git
  become: yes

- name: Check if homebrew is installed and configured
  shell: command -v brew
  ignore_errors: yes
  register: check_homebrew_installed

- name: Decide if should install homebrew
  set_fact:
    should_install_homebrew: "{{ check_homebrew_installed is failed }}"

- name: Install homebrew
  shell: "/bin/bash {{ download_homebrew_installation_script.dest }}"
  environment:
    NONINTERACTIVE: "1"
  when: should_install_homebrew

- name: Set homebrew prefix
  set_fact:
    homebrew_prefix: "/home/linuxbrew/.linuxbrew"

- name: Add homebrew path to .profile
  blockinfile:
    block: 'eval "$({{ homebrew_prefix }}/bin/brew shellenv)"'
    path: "{{ ansible_user_dir }}/.profile"
    backup: yes
    marker: "# {mark} ANSIBLE MANAGED BLOCK - homebrew"
