---
- name: Notify user that they should manually install Chrome extensions
  pause:
    prompt: |
      Please install chrome extensions.
      Press enter to automatically open their pages on chrome.
  when: "{{prompt_for_manual_actions}}"

- name: Open Chrome extensions pages
  shell: "google-chrome 'https://chrome.google.com/webstore/detail/{{ item }}'"
  loop:
    - jeoacafpbcihiomhlakheieifhpjdfeo  # Disconnect
    - fihnjjcciajhdojfnbdddfaoknhalnja  # I don't care about cookies
    - bcjindcccaagfpapjjmafapmmgkkhgoa  # JSON Formatter
    - hdokiejnpimakedhajhdlcegeplioahd  # LastPass
    - laookkfknpbbblfpciffpaejjkokdgca  # Momentum
    - fjcldmjmjhkklehbacihaiopjklihlgg  # News Feed Eradicator
    - jlmafbaeoofdegohdhinkhilhclaklkp  # OctoLinker
    - bkhaagjahfmjljalopjnoealnfndnagc  # Octotree - GitHub code tree
    - hlepfoohegkhhmjieoechaddaejaokhf  # Refined GitHub
    - niloccemoadcdkdjlinkgdfekeahmflj  # Save to Pocket
    - epcnnfbjfcgphgdmggkamkmgojdagdnn  # uBlock
    - ldgiafaliifpknmgofiifianlnbgflgj  # Ugly Email
    - egmbedhkleiholijlmnlhgcflooajdnb  # Unified Docs Switcher
    - gppongmhjkpfnbhagpmjfkannfbllamg  # Wappalyzer
    - ppaojnbmmaigjmlpjaldnkgnklhicppk  # Webtime Tracker
    - pebcgebefnbdkgpkkeelbpbgijmjackb  # Kumta - Home Front Command alerts
  when: "{{prompt_for_manual_actions}}"

- name: Notify user that they should login to GitHub CLI
  pause:
    prompt: |
      Please login to GitHub CLI. 
      Press enter to start.
  when: "{{prompt_for_manual_actions}}"

- name: Open Konsole for login to GitHub CLI
  shell: "konsole -e gh auth login --web"
  when: "{{prompt_for_manual_actions}}"
