---
- name: Notify user that they should manually install Chrome extensions
  pause:
    prompt: |
      Please install chrome extensions.
      Press enter to automatically open their pages on chrome.

- name: Open Chrome extensions pages
  # TODO only do this when not installed
  shell: "google-chrome 'https://chrome.google.com/webstore/detail/{{ item }}'"
  loop:
    - jeoacafpbcihiomhlakheieifhpjdfeo  # Disconnect
    - fihnjjcciajhdojfnbdddfaoknhalnja  # I don't care about cookies
    - bcjindcccaagfpapjjmafapmmgkkhgoa  # JSON Formatter
    - hdokiejnpimakedhajhdlcegeplioahd  # LastPass
    - laookkfknpbbblfpciffpaejjkokdgca  # Momentum
    - fjcldmjmjhkklehbacihaiopjklihlgg  # News Feed Eradicator
    - jlmafbaeoofdegohdhinkhilhclaklkp  # OctoLinker
    - bkhaagjahfmjljalopjnoealnfndnagc  # Octotree - GitHub code tree
    - hlepfoohegkhhmjieoechaddaejaokhf  # Refined GitHub
    - niloccemoadcdkdjlinkgdfekeahmflj  # Save to Pocket
    - epcnnfbjfcgphgdmggkamkmgojdagdnn  # uBlock
    - ldgiafaliifpknmgofiifianlnbgflgj  # Ugly Email
    - egmbedhkleiholijlmnlhgcflooajdnb  # Unified Docs Switcher
    - gppongmhjkpfnbhagpmjfkannfbllamg  # Wappalyzer
    - ppaojnbmmaigjmlpjaldnkgnklhicppk  # Webtime Tracker
    - pebcgebefnbdkgpkkeelbpbgijmjackb  # Kumta - Home Front Command alerts

- name: Check GitHub CLI auth status
  shell: gh auth status
  ignore_errors: yes
  register: gh_auth_status

- name: GitHub CLI authentication
  block:
    - name: Notify user that they should login to GitHub CLI
      pause:
        prompt: |
          Please login to GitHub CLI.
          Press enter to start.

    - name: Open Konsole for login to GitHub CLI
      shell: "konsole -e gh auth login --web"

  when: "{{ gh_auth_status.rc != 0 }}"

- name: stat SSH key
  stat:
    path: "{{ansible_user_dir}}/.ssh/id_rsa"
  register: stat_ssh_key

- name: SSH key creation
  block:
    - name: Request user input for SSH key passphrase
      pause:
        prompt: "Please enter passphrase for SSH key: "
      register: ssh_key_passphrase

    - name: Generate an OpenSSH keypair with the default values (4096 bits, rsa) and encrypted private key
      openssh_keypair:
        path: "{{ansible_user_dir}}/.ssh/id_rsa"
        passphrase: "{{ssh_key_passphrase}}"
        mode: "0600"

    # TODO notify user to add public key to wherever needed

  when: "{{stat_update_stamp.stat is not defined or not stat_update_stamp.stat.exists}}"

- name: Configure git user email
  block:
    - name: Request user email for git configuration
      pause:
        prompt: "Please enter user email for git configuration: "
      register: git_user_email

    - name: Configure git user email
      git_config:
        name: user.email
        value: "{{git_user_email}}"
        scope: global

  when: "{{ not git_user_email_is_defined }}"
