- name: Install personal tools (apt)
  apt:
    name:
      - openscad
      - kazam
      - pinta
  become: yes

- name: Install personal tools (flatpak)
  community.general.flatpak:
    name:
      - com.ultimaker.cura
      - org.audacityteam.Audacity
      - com.spotify.Client
      - org.telegram.desktop

- name: Install Steam
  community.general.flatpak:
    name:
      - com.valvesoftware.Steam
  when: computer_type == "personal"

- name: Remove packages I installed with flatpak (apt)
  apt:
    name:
      - code  # VS Code
      - steam
      - zoom
    state: absent
  become: yes

- name: Remove packages I installed with flatpak (snap)
  snap:
    name:
      - postman
      - telegram-desktop
      - spotify
    state: absent
  become: yes

- name: Remove packages I installed with flatpak (from AppImage, and various files)
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - /opt/cura.AppImage
    - /usr/bin/cura
    - /usr/local/share/applications/cura-icon.png
    - /usr/local/share/applications/com.ultimaker.cura.desktop
    - /opt/audacity.AppImage
    - /usr/bin/audacity
    - "{{ ansible_user_dir }}/.local/share/applications/spotify_spotify.desktop"
  become: yes
