- name: Add specified Inkscape PPA
  ansible.builtin.apt_repository:
    repo: ppa:inkscape.dev/stable
    update_cache: false  # We update in the next task
  become: yes

- name: Add specified OpenShot PPA
  ansible.builtin.apt_repository:
    repo: ppa:openshot.developers/ppa
    update_cache: true
  become: yes

- name: Install personal tools (apt)
  apt:
    name:
      - openscad
      - kazam
      - pinta
      - inkscape
      - openshot-qt
      - python3-openshot
  become: yes

- name: Install personal tools (flatpak)
  community.general.flatpak:
    name:
      - com.ultimaker.cura
      - org.audacityteam.Audacity
      - com.spotify.Client
      - org.telegram.desktop
      - io.gitlab.adhami3310.Footage
    state: latest

- name: Install Steam
  community.general.flatpak:
    name:
      - com.valvesoftware.Steam
  when: computer_type == "personal"
