- name: Install personal tools (snap)
  snap:
    name:
      - telegram-desktop
      - spotify
  become: yes

- name: Install personal tools (apt)
  apt:
    name:
      - openscad
  become: yes

- name: Install Kazam
  pip:
    name:
      - xdg  # Required for Kazam
      - Kazam
  become: yes

- name: Add Pinta apt repository into sources list
  apt_repository:
    repo: "ppa:pinta-maintainers/pinta-stable"
    update_cache: yes
  become: yes

- name: Install Pinta
  apt:
    name: pinta
  become: yes

- name: Download Audacity
  get_url:
    url: "https://github.com/audacity/audacity/releases/download/Audacity-{{audacity_version}}/audacity-linux-{{audacity_version}}-{{ansible_architecture}}.AppImage"
    dest: /opt/audacity.AppImage
    mode: '0755'
  become: yes
  register: download_audacity

- name: Create a symlink to Audacity
  file:
    src: "{{download_audacity.dest}}"
    dest: /usr/bin/audacity
    state: link
  become: yes

- name: Install Steam
  apt:
    deb: https://repo.steampowered.com/steam/archive/precise/steam_latest.deb
  become: yes

- name: Download Cura
  get_url:
    url: "https://software.ultimaker.com/cura/Ultimaker_Cura-{{cura_version}}.AppImage"
    dest: /opt/cura.AppImage
    mode: '0755'
  become: yes
  register: download_cura

- name: Create a symlink to Cura
  file:
    src: "{{download_cura.dest}}"
    dest: /usr/bin/cura
    state: link
  register: cura_symlink
  become: yes

- name: Copy Cura icon
  copy:
    src: "{{playbook_dir}}/configuration/cura-icon.png"
    dest: "/usr/local/share/applications/cura-icon.png"
    mode: 0644
  register: cura_icon
  become: yes

- name: Create a desktop entry for Cura
  template:
    src: "{{playbook_dir}}/configuration/com.ultimaker.cura.desktop.j2"
    dest: "/usr/local/share/applications/com.ultimaker.cura.desktop"
    mode: 0644
  become: yes
