- name: Install personal tools (snap)
  snap:
    name:
    - telegram-desktop
    - spotify
  become: yes

# TODO kazam for screen casting
# TODO pinta for image editing
# TODO audacity - personal only
# TODO steam - personal only