- name: Install personal tools (apt)
  apt:
    name:
      - openscad
      - kazam
      - pinta
  become: yes

- name: Install personal tools (flatpak)
  community.general.flatpak:
    name:
      - com.ultimaker.cura
      - org.audacityteam.Audacity
      - com.spotify.Client
      - org.telegram.desktop
      - io.gitlab.adhami3310.Footage

- name: Install Steam
  community.general.flatpak:
    name:
      - com.valvesoftware.Steam
  when: computer_type == "personal"
