- name: Check architecture of packages
  shell: dpkg --print-architecture
  register: dpkg_print_architecture

- name: Set packages_architecture
  set_fact:
    packages_architecture: "{{dpkg_print_architecture.stdout}}"

- name: Create directory for setup temporary files
  file:
    path: "{{temp_dir}}"
    state: directory

- name: Create initial user zsh_completion file
  template:
    src: "{{playbook_dir}}/configuration/empty.j2"
    dest: "{{temp_dir}}/user_zsh_completion"
    mode: "0640"
    force: yes
  register: create_user_zsh_completion

- name: Set user_zsh_completion_file_path
  set_fact:
    user_zsh_completion_file_path: "{{create_user_zsh_completion.dest}}"

- name: Running apt update if was not run in the last 7 days
  apt:
    update_cache: yes
    cache_valid_time: "{{ 0 if force_apt_update else (60 * 60 * 24 * 7) }}"
  become: yes

- name: Set JetBrains IDEs
  set_fact:
    jetbrains_ides: "{{ work_jetbrains_ides if computer_type == 'work' else personal_jetbrains_ides}}"

- name: Install flatpak
  import_role:
    name: don_rumata.ansible_role_install_flatpak
