- name: Check architecture of packages
  shell: dpkg --print-architecture
  register: dpkg_print_architecture

- name: Set packages_architecture
  set_fact:
    packages_architecture: "{{dpkg_print_architecture.stdout}}"

- name: Create directory for setup temporary files
  file:
    path: "{{temp_dir}}"
    state: directory

- name: Create initial bashrc file
  copy:
    src: "{{playbook_dir}}/configuration/bashrc"
    dest: "{{temp_dir}}/bashrc"
  register: create_bashrc

- name: Set bashrc_file_path
  set_fact:
    bashrc_file_path: "{{create_bashrc.dest}}"

- name: Read git config
  git_config:
    list_all: yes
  register: git_config_result

- name: Set git_user_email_is_defined
  set_fact:
    git_user_email_is_defined: git_config_result.config_values["user.email"] is defined
