- name: Check architecture of packages
  shell: dpkg --print-architecture
  register: dpkg_print_architecture

- set_fact:
    packages_architecture: "{{dpkg_print_architecture.stdout}}"

- name: Create directory for setup temporary files
  file:
    path: "{{temp_dir}}"
    state: directory

- name: Create initial bashrc file
  copy:
    src: "{{playbook_dir}}/configuration/bashrc"
    dest: "{{temp_dir}}/bashrc"
  register: create_bashrc

- set_fact:
    bashrc_file_path: "{{create_bashrc.dest}}"

