---
host_vars_file_path: "{{ playbook_dir }}/vars/host.yml"
prompt_for_manual_actions: yes
force_apt_update: no
configure_kde: yes
temp_dir: /tmp/pc-setup
dive_version: 0.10.0
postman_snap_channel: v9/stable
audacity_version: 3.2.1
cura_version: 5.2.1
add_ssh_key_to_github: yes
required_chrome_extension_ids:
  - jeoacafpbcihiomhlakheieifhpjdfeo  # Disconnect
  - fihnjjcciajhdojfnbdddfaoknhalnja  # I don't care about cookies
  - bcjindcccaagfpapjjmafapmmgkkhgoa  # JSON Formatter
  - hdokiejnpimakedhajhdlcegeplioahd  # LastPass
  - laookkfknpbbblfpciffpaejjkokdgca  # Momentum
  - fjcldmjmjhkklehbacihaiopjklihlgg  # News Feed Eradicator
  - jlmafbaeoofdegohdhinkhilhclaklkp  # OctoLinker
  - bkhaagjahfmjljalopjnoealnfndnagc  # Octotree - GitHub code tree
  - hlepfoohegkhhmjieoechaddaejaokhf  # Refined GitHub
  - niloccemoadcdkdjlinkgdfekeahmflj  # Save to Pocket
  - epcnnfbjfcgphgdmggkamkmgojdagdnn  # uBlock
  - ldgiafaliifpknmgofiifianlnbgflgj  # Ugly Email
  - egmbedhkleiholijlmnlhgcflooajdnb  # Unified Docs Switcher
  - gppongmhjkpfnbhagpmjfkannfbllamg  # Wappalyzer
  - ppaojnbmmaigjmlpjaldnkgnklhicppk  # Webtime Tracker
  - pebcgebefnbdkgpkkeelbpbgijmjackb  # Kumta - Home Front Command alerts
cura_configuration:
  - { section: "general", option: "auto_slice", value: "True" }
  - { section: "general", option: "accepted_user_agreement", value: "True" }
  - { section: "cura", option: "active_setting_visibility_preset", value: "all" }
settings_file_path: "{{ ansible_user_dir }}/.config/pc-setup/settings.json"
personal_jetbrains_ides:
  - goland
  - pycharm-professional
work_jetbrains_ides:
  - goland
  - pycharm-community
  - intellij-idea-community
jetbrains_ides_configuration:
  - { file_path: "options/other.xml", xpath: "/application/component[@name='PropertiesComponent']/property[@name='NonModalCommitCustomization.IsApplied']", value: "true" }
  - { file_path: "options/other.xml", xpath: "/application/component[@name='PropertiesComponent']/property[@name='NonModalCommitPromotionState']", value: "SHOWN" }
  - { file_path: "options/vcs.xml", xpath: "/application/component[@name='VcsApplicationSettings']/option[@name='COMMIT_FROM_LOCAL_CHANGES']", value: "false" }
  - { file_path: "options/editor.xml", xpath: "/application/component[@name='EditorSettings']/option[@name='IS_WHEEL_FONTCHANGE_ENABLED']", value: "true" }
  - { file_path: "options/editor.xml", xpath: "/application/component[@name='YamlEditorOptions']/option[@name='useSmartPaste']", value: "false" }
  - { file_path: "options/editor-font.xml", xpath: "/application/component[@name='DefaultFont']/option[@name='FONT_SIZE']", value: "14" }
  - { file_path: "options/editor-font.xml", xpath: "/application/component[@name='DefaultFont']/option[@name='FONT_FAMILY']", value: "JetBrains Mono" }
  - { file_path: "options/linux/keymap.xml", xpath: "/application/component[@name='KeymapManager']/active_keymap[@name='Or_Keymap']", value: "" }
ubuntu_archives_country_code: il
vs_code_deb_file_regexp: "code_(.+)_{{ packages_architecture }}.deb"

# Used by geerlingguy.docker:
docker_compose_version: v2.12.2

# Used by geerlingguy.nodejs:
nodejs_version: 16.x

# Used by geerlingguy.go:
go_version: 1.18.7
# Calculate by: curl -s https://dl.google.com/go/go1.18.7.linux-amd64.tar.gz | sha256sum
go_checksum: 6c967efc22152ce3124fc35cdf50fc686870120c5fd2107234d05d450a6105d8

# Used by avanov.pyenv:
pyenv_env: user
pyenv_global: 3.10.1
pyenv_python_versions:
  - "{{ pyenv_global }}"
pyenv_virtualenvs: []

# Used by robertdebock.terraform:
terraform_version: 1.3.3
