---
host_vars_file_path: "{{ playbook_dir }}/vars/host.yml"
prompt_for_manual_actions: yes
force_apt_update: no
configure_gnome: yes
temp_dir: /tmp/pc-setup
dive_version: 0.10.0
add_ssh_key_to_github: yes
default_chrome_extension_conf:
  external_update_url: "https://clients2.google.com/service/update2/crx"
required_chrome_extension_ids:
  - jeoacafpbcihiomhlakheieifhpjdfeo  # Disconnect
  - fihnjjcciajhdojfnbdddfaoknhalnja  # I don't care about cookies
  - bcjindcccaagfpapjjmafapmmgkkhgoa  # JSON Formatter
  - nngceckbapebfimnlniiiahkandclblb  # BitWarden
  - laookkfknpbbblfpciffpaejjkokdgca  # Momentum
  - fjcldmjmjhkklehbacihaiopjklihlgg  # News Feed Eradicator
  - jlmafbaeoofdegohdhinkhilhclaklkp  # OctoLinker
  - bkhaagjahfmjljalopjnoealnfndnagc  # Octotree - GitHub code tree
  - hlepfoohegkhhmjieoechaddaejaokhf  # Refined GitHub
  - niloccemoadcdkdjlinkgdfekeahmflj  # Save to Pocket
  - epcnnfbjfcgphgdmggkamkmgojdagdnn  # uBlock
  - ldgiafaliifpknmgofiifianlnbgflgj  # Ugly Email
  - egmbedhkleiholijlmnlhgcflooajdnb  # Unified Docs Switcher
  - gppongmhjkpfnbhagpmjfkannfbllamg  # Wappalyzer
  - ppaojnbmmaigjmlpjaldnkgnklhicppk  # Webtime Tracker
  - pebcgebefnbdkgpkkeelbpbgijmjackb  # Kumta - Home Front Command alerts
  - hpoiflhmfklhfcfpibmdmpeonphmdbda  # Home Assistant
  - gphhapmejobijbbhgpjhcjognlahblep  # GNOME Shell integration
cura_configuration:
  - { section: "general", option: "auto_slice", value: "True" }
  - { section: "general", option: "accepted_user_agreement", value: "True" }
  - { section: "cura", option: "active_setting_visibility_preset", value: "all" }
config_dir: "{{ ansible_user_dir }}/.config/pc-setup"
settings_file_path: "{{ config_dir }}/settings.json"
wallpaper_path: "{{ config_dir }}/wallpaper.jpg"
personal_jetbrains_ides:
  - goland
  - pycharm-professional
work_jetbrains_ides:
  - goland
  - pycharm-community
  - intellij-idea-community
jetbrains_ides_configuration:
  - { file_path: "options/other.xml", xpath: "/application/component[@name='PropertiesComponent']/property[@name='NonModalCommitCustomization.IsApplied']", value: "true" }
  - { file_path: "options/other.xml", xpath: "/application/component[@name='PropertiesComponent']/property[@name='NonModalCommitPromotionState']", value: "SHOWN" }
  - { file_path: "options/vcs.xml", xpath: "/application/component[@name='VcsApplicationSettings']/option[@name='COMMIT_FROM_LOCAL_CHANGES']", value: "false" }
  - { file_path: "options/editor.xml", xpath: "/application/component[@name='EditorSettings']/option[@name='IS_WHEEL_FONTCHANGE_ENABLED']", value: "true" }
  - { file_path: "options/editor.xml", xpath: "/application/component[@name='YamlEditorOptions']/option[@name='useSmartPaste']", value: "false" }
  - { file_path: "options/editor-font.xml", xpath: "/application/component[@name='DefaultFont']/option[@name='FONT_SIZE']", value: "14" }
  - { file_path: "options/editor-font.xml", xpath: "/application/component[@name='DefaultFont']/option[@name='FONT_FAMILY']", value: "JetBrains Mono" }
  - { file_path: "options/linux/keymap.xml", xpath: "/application/component[@name='KeymapManager']/active_keymap[@name='Or_Keymap']", value: "" }
ubuntu_archives_country_code: il
vs_code_deb_file_regexp: "code_(.+)_{{ packages_architecture }}.deb"
wallpapers_s3_base_url: "https://or-public-wallpapers-2.s3.eu-central-1.amazonaws.com"
wallpaper_by_computer_type:
  personal: "alexander_stream_estuary_side_stones_improved.jpg"
  work: "carmel_forest_improved.jpg"
favorite_apps:
  personal:
    - google-chrome.desktop
    - org.gnome.Nautilus.desktop
    - org.gnome.Terminal.desktop
    - com.spotify.Client.desktop
  work:
    - google-chrome.desktop
    - org.gnome.Nautilus.desktop
    - org.gnome.Terminal.desktop
    - com.spotify.Client.desktop
    - lens-desktop.desktop
    - com.slack.Slack.desktop

# Used by geerlingguy.docker:
docker_compose_version: v2.12.2

# Used by geerlingguy.nodejs:
nodejs_version: 20.x

# Used by geerlingguy.go:
go_version: 1.21.1
# Copy checksum from https://go.dev/dl/
go_checksum: b3075ae1ce5dab85f89bc7905d1632de23ca196bd8336afd93fa97434cfa55ae

# Used by staticdev.pyenv:
pyenv_env: user
pyenv_python_versions: &pyenv_python_versions
  - 3.11.6
pyenv_global: *pyenv_python_versions
pyenv_virtualenvs: []
pyenv_update_git_install: yes

# Used by robertdebock.terraform:
terraform_version: 1.4.6
