name: Test
on: [push]
jobs:
  test:
    runs-on: ubuntu-20.04  # Should actually be 21.10, but GH Actions currently supports only 18.04 and 20.04
    steps:
      - uses: actions/checkout@v2
      - run: |
          bash -c "ANSIBLE_BECOME_ASK_PASS=0 ${GITHUB_WORKSPACE}/setup.sh --extra-vars \"@/${GITHUB_WORKSPACE}/tests/test_vars.yml\""